### ISSUE TITLE
Unable to delete vertex or edge from the titan stored database

### ISSUE THREAD

**Issue by saran-vit** [adurrive/brownie.js#2]
Hi

Thanks for the library it's really helpful to develop graph database using node.js.

I am trying to delete already created vertex or edge graph from the stored titan but it's not working could you tell me is the functionally available in the library.

Here is what i tried,

// Query by key property
		var deleteDomain = DomainModel({
			properties: {
				id: parseInt(req.params.id)
			}
		});
	
		deleteDomain.get()
			.then(function(domains) {
				var Graph = brownie.Graph;
				var graph = new Graph(domains);
		
				graph.delete(req.params.id);
				graph.save()
					.then(function(domain) {
						res.status(200).json({ msg: domain });
					})
					.catch(function(err) {
						res.status(412).json({ err: err.message });
					});
					
			})
			.catch(function(err) {
				res.status(412).json({ err: err.message });
			});

**Comment by adurrive** [comment]
Hi, it is indeed possible! You have some useful examples in /test/vertices.js and /test/edges.js.

In your example, either one or the other of the following should work:
```javascript
var deleteDomain = DomainModel({
  properties: {
    id: parseInt(req.params.id)
  },
  remove: true
});
deleteDomain.save()
.then(...)
.catch(...);
```

or:
```javascript
var deleteDomain = DomainModel({
  properties: {
    id: parseInt(req.params.id)
  }
});
deleteDomain.delete();
deleteDomain.save()
.then(...)
.catch(...);
```
